version: "3"

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: mongodb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
