version: "3"

services:
  db:
    container_name: project_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: mongodb

  app:
    container_name: project_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

  api:
    container_name: project_api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
